apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: toolforge-build-service
bases:
  - ../base-tekton
  - ../base
resources:
  - persistent-volume-claim.yaml
patches:
  - auth-patch.yaml
