apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: toolforge-build-service
bases:
  - ../base-tekton
  - ../base
patches:
  - auth-patch.yaml

# needed to be able to patch inside lists without replacing them
patchesJson6902:
  - path: toolforge-buildpacks-phases-patch.json
    target:
        version: v1beta1
        kind: Task
        name: toolforge-buildpacks-phases
  - path: tekton-pipelines-controller-patch.json
    target:
        version: v1
        kind: Deployment
        name: tekton-pipelines-controller
  - path: tekton-pipelines-webhook-patch.json
    target:
        version: v1
        kind: Deployment
        name: tekton-pipelines-webhook
