apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: toolforge-build-service
resources:
  - tekton-pipelines.yaml

# needed to be able to patch inside lists without replacing them
patchesJson6902:
  - path: tekton-pipelines-controller-patch.json
    target:
      version: v1
      kind: Deployment
      name: tekton-pipelines-controller
  - path: tekton-pipelines-webhook-patch.json
    target:
      version: v1
      kind: Deployment
      name: tekton-pipelines-webhook
